export interface User {
  id: string;
  email: string;
}

export type WorkspaceRole = "member" | "admin" | "owner";

export interface Workspace {
  id: string;
  name: string;
  createdAt: string;
  role?: WorkspaceRole;
}

export interface Project {
  id: string;
  workspaceId: string;
  name: string;
  baseUrl: string;
  createdAt: string;
}

export interface Scan {
  id: string;
  projectId: string;
  workspaceId: string;
  requestedUrl: string;
  finalUrl: string | null;
  viewports: string[];
  aiMode: "off" | "mock" | "anthropic";
  status:
    | "QUEUED"
    | "INITIALIZING"
    | "LOADING_PAGE"
    | "COLLECTING_DATA"
    | "RUNNING_DETECTORS"
    | "AI_ANALYSIS"
    | "PROCESSING_RESULTS"
    | "COMPLETED"
    | "PARTIALLY_COMPLETED"
    | "FAILED";
  currentStep: string | null;
  failureReason: string | null;
  score: number | null;
  aiTelemetry: Record<string, unknown> | null;
  scanMetadata?: Record<string, unknown> | null;
  crawlMode?: string;
  startedAt: string | null;
  completedAt: string | null;
  createdAt: string;
}

export interface ScanPage {
  id: string;
  scanId: string;
  url: string;
  viewportName: string;
  viewportWidth: number;
  viewportHeight: number;
  loadState: "loaded" | "timeout" | "failed";
  screenshotStorageKeys: string[];
  /** Freshly-signed URLs generated by the API for this response — never
   * cached client-side beyond the current page load, since they expire. */
  screenshotUrls: string[];
}

export interface IssueSummary {
  totalIssues: number;
  critical: number;
  high: number;
  medium: number;
  low: number;
}

export type IssueSeverity = "critical" | "high" | "medium" | "low";

export interface UiIssue {
  issueId: string;
  scanId: string;
  pageId: string;
  category: string;
  issueType: string;
  title: string;
  description: string;
  severity: IssueSeverity;
  confidence: number;
  url: string;
  viewport: { name: string; width: number; height: number };
  element?: { selector: string; boundingBox?: { x: number; y: number; width: number; height: number } };
  evidence: Record<string, unknown>;
  aiExplanation?: string;
  aiValidation?: { provider: string; model: string; decision: string; aiConfidence: number };
  suggestedFix?: string;
  detector: { id: string; version: string; source: string };
  rootCauseSignature?: string;
  affectedElementCount: number;
  responsiveRecurrence?: { viewportsAffected: string[]; viewportsScanned: string[]; narrowViewportOnly: boolean };
  createdAt: string;
  feedbackStatus: "open" | "valid" | "false_positive" | "ignored";
}
