import { BoundingBox } from "./page-context.types";

export type IssueSeverity = "critical" | "high" | "medium" | "low";

export type IssueCategory =
  | "image"
  | "network"
  | "layout"
  | "content"
  | "accessibility"
  | "technical"
  | "visual-ai";

export type DetectorSource = "deterministic" | "computer-vision" | "ocr" | "ai";

/**
 * What a detector emits before validation/dedup/scoring. Confidence here
 * is the detector's own local estimate; the Issue Engine may adjust it.
 */
export interface IssueCandidate {
  category: IssueCategory;
  issueType: string;
  title: string;
  description: string;
  severity: IssueSeverity;
  confidence: number; // 0.0 - 1.0
  element?: {
    selector?: string;
    tagName?: string;
    text?: string;
    boundingBox?: BoundingBox;
  };
  evidence: {
    screenshotPath?: string;
    annotatedScreenshotPath?: string;
    resourceUrl?: string;
    httpStatus?: number;
    consoleMessage?: string;
    measuredValue?: string;
    expectedValue?: string;
    raw?: Record<string, unknown>;
  };
  suggestedFix?: string;
  /**
   * Human-friendly explanation generated by the AI Explainer role (Phase
   * 2). Distinct from `description` (the detector's own technical
   * description) — this is the "translate for a non-technical reader"
   * layer, and is only ever additive: its absence never affects whether
   * an issue is reported.
   */
  aiExplanation?: string;
  /**
   * Present only when this candidate went through AI validation
   * (currently: ambiguous element-overlap candidates). Kept as an
   * auditable record of what the AI was shown and what it decided —
   * per the Phase 2 security requirement to "record what content was
   * sent to AI for auditability."
   */
  aiValidation?: {
    provider: string;
    model: string;
    decision: "confirm" | "suppress" | "needs_more_evidence";
    aiConfidence: number;
    evidenceSummary: string;
    cropPath?: string;
    promptVersion: string;
  };
  detector: {
    id: string;
    version: string;
    source: DetectorSource;
  };
  /**
   * Used by the Deduplicator to group equivalent findings across
   * viewports/pages (e.g. same failed resource URL, same selector pattern).
   */
  rootCauseSignature?: string;
}

/**
 * Final, persisted shape. Every detector — deterministic, CV, OCR, AI —
 * ultimately produces this same shape so the report writer, future API,
 * and dashboard never depend on detector-specific fields.
 */
export interface UiIssue extends IssueCandidate {
  issueId: string;
  scanId: string;
  pageId: string;
  url: string;
  viewport: {
    name: string;
    width: number;
    height: number;
  };
  browser: {
    engine: "chromium" | "webkit" | "firefox" | string;
    version?: string;
  };
  affectedElementCount: number;
  createdAt: string;
  /**
   * Populated by the Responsive Delta correlator (issue-engine) after all
   * viewports in a scan have been assembled. Tells the reader whether this
   * issue is a narrow-viewport-only regression versus a problem present
   * everywhere — a strong signal for prioritization that a single-viewport
   * detector run can never produce on its own.
   */
  responsiveRecurrence?: {
    viewportsAffected: string[];
    viewportsScanned: string[];
    narrowViewportOnly: boolean;
  };
}
